#!/bin/bash

#
# build - Automatically builds an AoAA example program from the command line
#
# Usage:
# $ build [-c] <filename>
# (no suffix on the filename)
#
# Options:
# -c: assemble .S file to object code only
#

set -euo pipefail

fileName=""
compileOnly=false
cFile="listing1-4.cpp"

while [[ $# -gt 0 ]]; do
	case "$1" in
	-c)
		compileOnly=true
		shift
		;;
	*)
		fileName="$1"
		shift
		;;
	esac
done

if [[ -z "$fileName" ]]; then
	echo "Usage: build [-c] <filename>" >&2
	exit 1
fi

# If the user inadvertently stuck a .s or .S suffix on the file name, abort before we get in trouble.

case "$fileName" in
*.S)
	echo "Argument should not have an .S suffix" >&2
	exit 1
	;;
*.s)
	echo "Argument should not have an .s suffix" >&2
	exit 1
	;;
esac

# Delete any stale executable/object file.
rm -f "$fileName" "$fileName".o

# If the -c option was provided, only assemble the .S file and produce a .o output file.
# Otherwise, compile both the .cpp and the .S file and produce an executable.
if $compileOnly; then
	g++ -c -o "$fileName".o "$fileName".S
else
	g++ -o "$fileName" "$cFile" "$fileName".S
fi
